version: "3.7"

services:
  checker:
    # build: checker
    image: mike0sv/sf_docker_check
    container_name: checker

  model:
    build:
      context: ./model
    image: model:5.12
    restart: always
    container_name: solution
    ports:
      - 5000:5000
