version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  features:
    build:
      context: ./features
    restart: always
    depends_on:
      - rabbitmq
    container_name: features

  model:
    build:
      context: ./model
    restart: always
    depends_on:
      - rabbitmq
    container_name: model

  metric:
    build:
      context: ./metric
    restart: always
    depends_on:
      - rabbitmq
    container_name: metric
    volumes:
      - ./metric.log:/usr/src/app/metric.log:z,rw
